export const store = {
    postsHome:{
        data:null,
    },
    listPost:{
        data:null,
    },
    listPostUser:{
        data:null,
    },
    listaUsuarios:{
        data:null,
    },
    dataPost:{
        data:null,
    },
    editarPost:{
        data:null,
    },
    postsFiltrados:{
        data:null,
    },
    categorias:{
        data:null
    },
    respuestaCategoria:{
        data:null
    },
    login:{
        data:null
    },
    dataUser:{
        data:null
    },
    respUser:{
        data:null
    },
    respLoginUser:{
        data: null
    },
    roleUser:{
        data:null
    },
    respuestaEditarUser:{
        data:null
    },
    rtaListPostGeneral:{
        data:null
    },
    respuestaEliminarPost:{
        data:null
    },
    respuestaSubirArchivos:{
        data:null
    },
    listMultimedia:{
        data:null
    },
    respuestaCreatePost:{
        data:null
    },    
    dataPostPath:{
        data:null
    },    
    respuestaCargarPublicidad:{
        data:null
    },    
    listPublicidades:{
        data:null
    },
    listPostOeste:{
        data:null
    },
    listCategoriaSinSub:{
        data:null
    },
    modoOscuro:{
        data:false
    },
    respuestaEliminarMultimedia:{
        data:null
    }, 
}