export const actionTypes = {

  //POSTEOS
  GET_RECIBIR_PUBLICACIONES: "GET_RECIBIR_PUBLICACIONES",
  SET_RECIBIR_PUBLICACIONES: "SET_RECIBIR_PUBLICACIONES",
  GET_RECIBIR_PUBLICACIONES_FILTRADAS: "GET_RECIBIR_PUBLICACIONES_FILTRADAS",
  SET_RECIBIR_PUBLICACIONES_FILTRADAS: "SET_RECIBIR_PUBLICACIONES_FILTRADAS",

  //LIST POST GENERAL
  GET_LIST_POST: "GET_LIST_POST",
  SET_LIST_POST: "SET_LIST_POST",
  RESPUESTA_LIST_POST: "RESPUESTA_LIST_POST",

  //LIST POST USER
  GET_LIST_POST_USER: "GET_LIST_POST_USER",
  SET_LIST_POST_USER: "SET_LIST_POST_USER",

  //EDITAR POST
  GET_EDITAR_POST: "GET_EDITAR_POST",
  SET_EDITAR_POST: "SET_EDITAR_POST",

  //ELIMINAR POST
  RESPUESTA_ELIMINAR_POST: "RESPUESTA_ELIMINAR_POST",
  SET_ELIMINAR_POST: "SET_ELIMINAR_POST",

  //DATA POST
  GET_DATA_POST: "GET_DATA_POST",
  SET_DATA_POST: "SET_DATA_POST",

  //CATEGORIAS
  RESPUESTA_CREAR_CATEGORIA: "RESPUESTA_CREAR_CATEGORIA",
  SET_CREAR_CATEGORIA: "SET_CREAR_CATEGORIA",
  SET_ELIMINAR_CATEGORIA: "SET_ELIMINAR_CATEGORIA",
  GET_RECIBIR_CATEGORIAS: "GET_RECIBIR_CATEGORIAS",
  SET_RECIBIR_CATEGORIAS: "SET_RECIBIR_CATEGORIAS",

  //CATEGORIAS SIN SUB
  GET_LIST_CATEGORIAS_SIN_SUB:"GET_LIST_CATEGORIAS_SIN_SUB",
  SET_LIST_CATEGORIAS_SIN_SUB:"SET_LIST_CATEGORIAS_SIN_SUB",

  //LOGIN
  VERIFICAR_INGRESO_LOGIN: "VERIFICAR_INGRESO_LOGIN",
  RESULT_VERIFICAR_LOGIN: "RESULT_VERIFICAR_LOGIN",
  RESPUESTA_LOGIN_USUARIO: "RESPUESTA_LOGIN_USUARIO",
  SET_LOGIN: "SET_LOGIN",

  //USER
  CREAR_USUARIO: "CREAR_USUARIO",
  SET_USUARIO_DATA: "SET_USUARIO_DATA",
  GET_USUARIO_DATA: "GET_USUARIO_DATA",
  RESPUESTA_USER: "RESPUESTA_USER",
  RESPUESTA_EDITAR_USER: "RESPUESTA_EDITAR_USER",
  SET_EDITAR_USUARIO: "SET_EDITAR_USUARIO",

  //ROLE USER
  SET_ROLE_USER: "SET_ROLE_USER",
  GET_ROLE_USER: "GET_ROLE_USER",

  //LISTA USUARIOS
  SET_LISTA_USUARIOS: "SET_LISTA_USUARIOS",
  GET_LISTA_USUARIOS: "GET_LISTA_USUARIOS",

  //SET_SUBIR_ARCHIVO
  SET_SUBIR_ARCHIVO: "SET_SUBIR_ARCHIVO",
  RESPUESTA_SUBIR_ARCHIVO: "RESPUESTA_SUBIR_ARCHIVO",

  //SET LIST MULTIMEDIA
  SET_LIST_MULTIMEDIA: "SET_LIST_MULTIMEDIA",
  GET_LIST_MULTIMEDIA: "GET_LIST_MULTIMEDIA",

  //SET CREATE POST
  SET_CREATE_POST: "SET_CREATE_POST",
  RESPUESTA_CREATE_POST: "RESPUESTA_CREATE_POST",
  
  //DATA POST
  SET_DATA_POST_PATH:"SET_DATA_POST_PATH",
  GET_DATA_POST_PATH:"GET_DATA_POST_PATH",

  //LIST PUBLICIDAD
  GET_LIST_PUBLICIDADES:"GET_LIST_PUBLICIDADES",
  SET_LIST_PUBLICIDADES:"SET_LIST_PUBLICIDADES",

  //CARGAR PUBLICIDAD
  SET_CARGAR_PUBLICIDAD:"SET_CARGAR_PUBLICIDAD",
  RESPUESTA_CARGAR_PUBLICIDAD:"RESPUESTA_CARGAR_PUBLICIDAD",


  //SET SUMAR VISITA
  SET_SUMAR_VISITA:"SET_SUMAR_VISITA",

  //LIST POST OESTE
  SET_RECIBIR_PUBLICACIONES_OESTE:"SET_RECIBIR_PUBLICACIONES_OESTE",
  GET_RECIBIR_PUBLICACIONES_OESTE:"GET_RECIBIR_PUBLICACIONES_OESTE",

  //MODO OSCURO
  GET_MODO_OSCURO:"GET_MODO_OSCURO",
  SET_MODO_OSCURO:"SET_MODO_OSCURO",

  //MODO OSCURO
  SET_ELIMINAR_MULTIMEDIA:"SET_ELIMINAR_MULTIMEDIA",  
  GET_ELIMINAR_MULTIMEDIA:"GET_ELIMINAR_MULTIMEDIA",  

};
